### PR TITLE
fix: remix action/loaders with redirect timeout

### LINKED ISSUE #395: Remix action/loaders with `redirect` return `504` error from cloudfront due to lambda timeout
using SST V: `0.0.357`

It seems Dax broke `redirect` in Remix with the latest streaming support addition. 
The following action
```ts
export async function action() {
  await db.increment()
  return redirect('/counter')
}
```
will timeout, but if you change the redirect to something like `json(some data)` it works.

## Reproduction
Deploy a new/existing project with sst, and trigger an action with a `redirect` response.
Here's a [template](https://github.com/kiliman/remix-vite-template) I used to reproduce the issue after running into it within my project

### LINKED ISSUE #4646: Remix action/loaders with `redirect` return `504` error from cloudfront due to lambda timeout
using SST V: `0.0.357`

It seems Dax broke `redirect` in Remix with the latest streaming support addition. 
The following action
```ts
export async function action() {
  await db.increment()
  return redirect('/counter')
}
```
will timeout, but if you change the redirect to something like `json(some data)` it works.

## Reproduction
Deploy a new/existing project with sst, and trigger an action with a `redirect` response.
Here's a [template](https://github.com/kiliman/remix-vite-template) I used to reproduce the issue after running into it within my project

### PR DESCRIPTION
**Pull request by sammyjoyce**
fixes sst/sst#4646

this issue is due to the [react-router redirect function](https://github.com/remix-run/react-router/blob/9d42655bc6eedd9a09d0c82c48406c8d9268260f/packages/router/utils.ts#L1542) that remix uses not including a body (as it's just a redirect, so is only setting headers)

streamified response with empty body ignores other response attributes, so we write a single whitespace

### CODE REVIEW

File: pkg/platform/functions/remix-server/regional-server.mjs [hunk 1]
```diff
@@ -113,13 +113,16 @@ const createApigHandler = (build) => {
...
-      );
-      await streamToNodeStream(reader.getReader(), responseStream);
+    );
+
+    if (response.body) {
+      await streamToNodeStream(response.body.getReader(), responseStream);
+    } else {
+      writer.write(" ");
       writer.end();
     }
```
Comment (blntrsz) [inline pkg/platform/functions/remix-server/regional-server.mjs]: Shouldn't we do a `writer.end()` in all cases?

```suggestion
      writer.write(" ");
    }
      writer.end();
```

Comment (sammyjoyce) [reply pkg/platform/functions/remix-server/regional-server.mjs]: Yes, but StreamToNodeStream already has writer.end(), so both cases already do. I'd be inclined to do away with that function and inline that branch, but left it is as is, assuming @thdxr would do that if he wanted it

**Review by thdxr — APPROVED** [review]

**Comment by thdxr** [comment]
thank you!
