### PR TITLE
aws.sst.StaticSite: add missing responseCode when passing errorPage

### LINKED ISSUE #481: aws.StaticSite errorPage issue
Version: 0.0.393

Currently it is not possible to use the errorPage field in the StaticSite construct.

```ts
const website = new sst.aws.StaticSite('Website', {
      path: 'website',
      indexPage: 'index.html',
      // wont work 
      // errorPage: 'index.html',
      // errorPage: '/index.html',
      domain: {
        name: 'example.com',
        redirects: [
          'www.example.com',
        ],
      },
      transform: {
        cdn: {
          customErrorResponses: [
            // works
            {
              errorCode: 404,
              responsePagePath: '/index.html',
              responseCode: 200,
            },
          ],
        }
      }
});
```
The deploy fails with message:
`CloudFront: UpdateDistribution, https response error StatusCode: 400, RequestID: XXX, IllegalUpdate: Your request must specify both ResponsePagePath and ResponseCode together or both should be empty.`

### LINKED ISSUE #4582: aws.StaticSite errorPage issue
Version: 0.0.393

Currently it is not possible to use the errorPage field in the StaticSite construct.

```ts
const website = new sst.aws.StaticSite('Website', {
      path: 'website',
      indexPage: 'index.html',
      // wont work 
      // errorPage: 'index.html',
      // errorPage: '/index.html',
      domain: {
        name: 'example.com',
        redirects: [
          'www.example.com',
        ],
      },
      transform: {
        cdn: {
          customErrorResponses: [
            // works
            {
              errorCode: 404,
              responsePagePath: '/index.html',
              responseCode: 200,
            },
          ],
        }
      }
});
```
The deploy fails with message:
`CloudFront: UpdateDistribution, https response error StatusCode: 400, RequestID: XXX, IllegalUpdate: Your request must specify both ResponsePagePath and ResponseCode together or both should be empty.`

### PR DESCRIPTION
**Pull request by mlafeldt**
fixes sst/sst#4582

### CODE REVIEW

**Comment by jayair** [comment]
Thanks!

File: pkg/platform/src/components/aws/static-site.ts [hunk 1]
```diff
@@ -569,29 +569,18 @@ export class StaticSite extends Component implements Link.Linkable {
...
+          customErrorResponses: [
+            {
+              errorCode: 403,
+              responsePagePath: interpolate`/${args.errorPage || indexPage}`,
+              responseCode: 200,
+            },
+            {
+              errorCode: 404,
+              responsePagePath: interpolate`/${args.errorPage || indexPage}`,
+              responseCode: 200,
```
Comment (unrevised6419) [inline pkg/platform/src/components/aws/static-site.ts]: Suggestion: Would be better to still keep 404 status.

```suggestion
              responseCode: 404,
```

**Comment by fwang** [comment]
Thanks @mlafeldt @iamandrewluca!

Made it to perserve the status code when error page is set.
